name: CI - Teste e Qualidade

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  test:
    name: Run Tests & Checks
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.18.4'
        otp-version: '28.0.2'

    - name: Install dependencies
      run: mix deps.get

    - name: Check formatting
      run: mix format --check-formatted

    - name: Run tests
      run: mix test
